#--------------LEET CODE---------------
#206. Reverse list

#Solution of Matvey Guralskiy
#https://github.com/MatveyGuralskiy
class Solution:
    def reverseList(self,head):
        pre = None     # Initialize prev pointer as NULL...
        cur = head     # Initialize the curr pointer as the head...
        while cur:     # Run a loop till curr points to NULL...
            temp = cur.next   # Initialize next pointer as the next pointer of curr...
            cur.next = pre    # Now assign the prev pointer to curr’s next pointer.
            pre = cur         # Assign curr to prev, next to curr...
            cur = temp
        return pre            # Return the prev pointer to get the reverse linked list...
    